main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    
    
    
    path('dashboard', views.dashboard, name='dashboard'),
    path('affecter_matieres_prof', views.affectation_matieres_professeur, name='affectation_matieres_professeur'),
    path('liste_matieres_professeur',views.liste_matieres_professeur,name='liste_matieres_professeur'),
    path('retirer_professeur/<int:id>', views.retirer_professeur, name='retirer_professeur'),
    path('modifier_ponderation/<int:matiere_id>/<int:nouvelle_ponderation>/', views.modifier_ponderation, name='modifier_ponderation'),
    path('cahier_de_text/', views.cahier_de_text, name='cahier_de_text'),
    path('enregistrer_seance/', views.enregistrer_seance, name='enregistrer_seance'),
    path('modifier_seance/<int:seance_id>/', views.modifier_seance, name='modifier_seance'),
    path('liste_seance/', views.liste_seance, name='liste_seance'),
    path('liste_seance_etudiant/', views.liste_seance_etudiant, name='liste_seance_etudiant'),
    path('info_seance/<int:seance_id>/', views.info_seance, name='info_seance'),
    path('valider_seance/<int:seance_id>/', views.valider_seance, name='valider_seance'),
    path('connexion',views.login_view,name='connexion'),
    path('reminder',views.recuperation_mdp,name='reminder'),
    path('deconnexion',views.logout_view,name='deconnexion'),
    path('changer_secretaire',views.changer_secretaire,name='changer_secretaire'),
    path('gestion_classe',views.gestion_classe,name='gestion_classe'),



    # touré-ydaou urls templates latex 30-04-2023

    path('etudiants-l1', views.etudiants_l1, name='etudiants_l1'),
    path('etudiants-l2', views.etudiants_l2, name='etudiants_l2'),
    path('etudiants-l3', views.etudiants_l3, name='etudiants_l3'),


    path('carte-etudiant/<str:id>/<str:niveau>', views.carte_etudiant, name='carte_etudiant'),
    path('diplome/<str:id>', views.diplome_etudiant, name='diplome_etudiant'),
    path('certificat_scolaire/<str:id>/<str:niveau>', views.certificat_scolaire, name='certificat_scolaire'),
    path('releve_notes/<str:id>/<str:id_semestre>', views.releve_notes, name='releve_notes'),
    path('releve_note_detail/<str:id>/<str:id_semestre>', views.releve_notes_detail, name="releve_notes_detail"),

    # urls permettant de générer les documents de manière groupée (pour un ensemble d'étudiants)
    path('releve_notes/<str:id_semestre>', views.releve_notes_semestre, name='releve_notes'),
    path('carte-etudiant/<str:niveau>', views.carte_etudiant_all, name='carte_etudiant'),
    path('diplomes', views.diplome_etudiant_all, name='diplome_etudiant'),



    # Abdoul-Malik urls notes
    path('evaluations/<int:id_matiere>', views.evaluations, name='evaluations'),
    path('add_evaluation/<int:id_matiere>', views.createNotesByEvaluation, name='add_evaluation'),
    path('edit_evaluation/<int:id>', views.editeNoteByEvaluation, name='edit_evaluation'),
    path('delete_evaluation/<int:id>', views.deleteEvaluation, name='delete_evaluation'),


                               #### Étudiants ####
    path('liste_des_etudiants/', views.etudiants, name='liste_des_etudiants'),
    path('liste_des_etudiants_suspendu/', views.etudiants_suspendu, name='liste_des_etudiants_suspendu'),
    path('detail_etudiant/<str:id>/', views.detailEtudiant, name='detail_etudiant'),    
    path('create_etudiant/', views.create_etudiant, name='create_etudiant'),
    path('update_etudiant/<str:id>/', views.create_etudiant, name='update_etudiant'),   
   
   
                            #### Tuteurs ####
    path('liste_des_tuteurs/', views.tuteurs, name='liste_des_tuteurs'),
    path('detail_tuteur/<int:id>/', views.detailTuteur, name='detail_tuteur'),
    path('create_tuteur/', views.create_tuteur, name='create_tuteur'),
    path('update_tuteur/<int:id>/', views.create_tuteur, name='update_tuteur'),



                            #### Matières ####
    path('liste_des_matieres/', views.matieres, name='liste_des_matieres'),
    path('detail_matiere/<int:id>/', views.detailMatiere, name='detail_matiere'),
    path('create_matiere/', views.create_matiere, name='create_matiere'),
    path('update_matiere/<int:id>/', views.create_matiere, name='update_matiere'),

   

    path('matieres/semestre/1/', views.matiere_semestre, {'semestre': 1}, name='matiere_semestre1'),
    path('matieres/semestre/2/', views.matiere_semestre, {'semestre': 2}, name='matiere_semestre2'),
    path('matieres/semestre/3/', views.matiere_semestre, {'semestre': 3}, name='matiere_semestre3'),
    path('matieres/semestre/4/', views.matiere_semestre, {'semestre': 4}, name='matiere_semestre4'),
    path('matieres/semestre/5/', views.matiere_semestre, {'semestre': 5}, name='matiere_semestre5'),
    path('matieres/semestre/6/', views.matiere_semestre, {'semestre': 6}, name='matiere_semestre6'),




                            #### UEs ####
    path('liste_des_ues/', views.ues, name='liste_des_ues'),
    path('detail_ue/<int:id>/', views.detailUe, name='detail_ue'),
    path('create_ue/', views.create_ue, name='create_ue'),
    path('update_ue/<int:id>/', views.create_ue, name='update_ue'),

                        
                            ### UE par semestre
    path('ues_semestre/semestre1/', views.ues_semestre, {'semestre': 'S1'}, name='ues_semestre1'),
    path('ues_semestre/semestre2/', views.ues_semestre, {'semestre': 'S2'}, name='ues_semestre2'),
    path('ues_semestre/semestre3/', views.ues_semestre, {'semestre': 'S3'}, name='ues_semestre3'),
    path('ues_semestre/semestre4/', views.ues_semestre, {'semestre': 'S4'}, name='ues_semestre4'),
    path('ues_semestre/semestre5/', views.ues_semestre, {'semestre': 'S5'}, name='ues_semestre5'),
    path('ues_semestre/semestre6/', views.ues_semestre, {'semestre': 'S6'}, name='ues_semestre6'),



                            #### Enseignant ####
    path('create_enseignant/', views.create_enseignant, name='create_enseignant'),
    path('enseignant_list/', views.enseignant_actif, name='enseignant_list'),
    path('enseignant_suspendu/', views.enseignant_inactif, name='enseignant_suspendu'),
    path('enseignant_detail/(?P<id>[0-9]+)\\Z/', views.enseignant_detail, name='enseignant_detail'),
    path('edit_enseignant/(?P<id>[0-9]+)\\Z/', views.edit_enseignant, name='edit_enseignant'),
    path('certificat_travail/(?P<id>[0-9]+)\\Z/', views.certificat_travail, name='certificat_travail'),

                        ### Information ###
    path('information_list/', views.information_list, name='information_list'),
    path('information_detail/(?P<id>[0-9]+)\\Z/', views.information_detail, name='information_detail'),
    path('create_information/', views.create_information, name='create_information'),
    path('edit_information/(?P<id>[0-9]+)\\Z/', views.edit_information, name='edit_information'),




## Malia clôture des semestres
    path('semestres/', views.semestres_courants, name='semestres'),
    path('semestres_clotures/', views.semestres_clotures, name='semestres_clotures'),
    path('cloturer_semestre/<str:semestre_id>/', views.cloturer_semestre, name='cloturer_semestre'),
    path('reactiver_semestre/<str:semestre_id>/', views.reactiver_semestre, name='reactiver_semestre'),


## Historique des semestres :
    path('semestre/<str:semestre_id>/historique/', views.historique_semestre, name='historique_semestre'),



### Liste des étudiants par semestres 
    path('liste-etudiants/semestre1/', views.liste_etudiants_par_semestre, {'semestre': 'S1'}, name='liste_etudiants_semestre1'),
    path('liste-etudiants/semestre2/', views.liste_etudiants_par_semestre, {'semestre': 'S2'}, name='liste_etudiants_semestre2'),
    path('liste-etudiants/semestre3/', views.liste_etudiants_par_semestre, {'semestre': 'S3'}, name='liste_etudiants_semestre3'),
    path('liste-etudiants/semestre4/', views.liste_etudiants_par_semestre, {'semestre': 'S4'}, name='liste_etudiants_semestre4'),
    path('liste-etudiants/semestre5/', views.liste_etudiants_par_semestre, {'semestre': 'S5'}, name='liste_etudiants_semestre5'),
    path('liste-etudiants/semestre6/', views.liste_etudiants_par_semestre, {'semestre': 'S6'}, name='liste_etudiants_semestre6'),

    path('passage_etudiants/', views.passage_etudiants, name='passage_etudiants'),












]

projet_ifnti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('maquette/', include('maquette.urls')),
    path('historique/', include('historiques.urls')),
    path('paiement/', include('paiement.urls')),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/templates/matieres/affectation_professeur.html
{% extends '../index.html' %}

{% load static %}

{% block content %}
       <div class="content">
                    <!-- lal -->
                    <div class="block block-rounded">
                        <div class="block-header">
                            <h3 class="block-title">Affectation Matieres</h3>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="block-content">
                                <p class="font-size-sm text-muted mb-3">Choisissez un enseignant dans la liste déroulante :</p>
                                <div class="form-group row mb-4">
                                    <label class="col-sm-2 col-form-label" for="enseignant">enseignant :</label>
                                    <div class="col-sm-10">
                                        <select class="form-control" name="enseignant" id="enseignant">
                                            {% for enseignant in enseignants %}
                                                <option name="enseignant" value="{{ enseignant.id }}">{{ enseignant.nom }} {{ enseignant.prenom }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <p class="font-size-sm text-muted mb-3">Cochez les matières à affecter avec leurs ponderation respective :</p>
                                <div class="form-group row mb-4">
                                    {% for matiere in matieres %}
                                        <div class="col-sm-6">
                                            <div class="custom-control custom-checkbox">
                                                <input class="custom-control-input matiere" type="checkbox" name="matieres[]" value="{{ matiere.libelle }}" id="{{ matiere.libelle }}">
                                                <label class="custom-control-label" for="{{ matiere.libelle }}">{{ matiere.libelle }}</label>
                                            </div>
                                            <select class="form-control form-control-sm ponderation mt-2 d-none" name="ponderations[]" id="{{ matiere.libelle }}-ponderation">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                            </select>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-12 text-center">
                                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        
                       
                        
                        
                        
                    </div>
                    <!-- END Normal -->

                    
                    
        </div>

		<script>
            // Affiche la pondération correspondante à la matière sélectionnée
            $('.matiere').change(function() {
                var matiere = $(this).attr('id');
                var ponderation = $('#' + matiere + '-ponderation');
                if ($(this).is(':checked')) {
                    ponderation.removeClass('d-none');
                } else {
                    ponderation.addClass('d-none');
                }
            });
        </script>

{% endblock %}

main/templates/matieres/create_matiere.html
{% extends '../index.html' %}

{% load static %}

{% block content %}

    <div id="content-wrapper">
        <div class="container-fluid">
            <div class="card mb-3">
                <div class="card-header">
                    <h3><i class="fas fa-table"></i> Enrégistrement d'une matière <a class="btn btn-sm btn-success" href="{% url 'main:liste_des_matieres' %}" style="padding: 8px; float: right; background-color: blue; color: white;"><i class="fas fa-chevron-left fa-lg"></i>
                        Retour</a></h3>
                </div>
                <div class="card-body">
                  <form class="form-horizontal" action="#" method="POST">
                    {% csrf_token %}

                
                    <div class="form-group row">
                        <label for="{{ form.codematiere.id_for_label }}" class="col-md-2 col-form-label">Code de la matière:</label>
                        <div class="col-md-10">
                            {{ form.codematiere }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="{{ form.libelle.id_for_label }}" class="col-md-2 col-form-label">Libellé de la matière:</label>
                        <div class="col-md-10">
                            {{ form.libelle }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="{{ form.ponderation.id_for_label }}" class="col-md-2 col-form-label">Coefficient:</label>
                        <div class="col-md-10">
                            {{ form.coefficient }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="{{ form.minValue.id_for_label }}" class="col-md-2 col-form-label">Valeur minimale:</label>
                        <div class="col-md-10">
                            {{ form.minValue }}
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="{{ form.ue.id_for_label }}" class="col-md-2 col-form-label">Ue:</label>
                        <div class="col-md-10">
                            {{ form.ue }}
                        </div>
                    </div>
                                     
                    <button class="btn btn-primary btn-block" type="submit"><i class="fas fa-database"></i> Enrégistrer &nbsp;&nbsp;&nbsp;<span></span></button>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/matieres/detailMatiere.html
{% extends '../index.html' %}

{% block content %}

<style>
    #etudiant{
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    #etudiant td,#etudiant th{
        border: 1px solid #ddd;
        padding: 8px;
    }
    #etudiant tr:nth-child(even){
        background-color: #e8c1f7;
    }
    #etudiant th{
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #d6eaf8;
    }
</style>

<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Détail de la matière {{matiere.libelle}}</h3>
        <a class="btn btn-sm btn-success" href="{% url 'main:liste_des_matieres' %}" style="padding: 8px; float: right; background-color: blue; color: white;"><i class="fas fa-chevron-left fa-lg"></i>
            Retour</a>
    </div>
    <div class="block-content block-content-full">
                <table id="etudiant">
            <thead>
                <tr>
                    <th class="text-center" style="width: 14%;">Code matière</th>
                    <th class="text-center" style="width: 20%;">Libéllé</th>
                    <th class="text-center" style="width: 40px;">Coefficient</th>
                    <th class="text-center" style="width: 50px;">Valeur minimale</th>
                    <th class="text-center" style="width: 20%;">Enseignant</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center font-size-sm">{{matiere.codematiere}}</td>
                    <td class="text-center font-size-sm">{{matiere.libelle}}</td>                  
                    <td class="text-center font-size-sm">{{matiere.coefficient}}</td>                  
                    <td class="text-center font-size-sm">{{matiere.minValue}}</td>                  
                    <td class="text-center font-size-sm">
                        {% if matiere.enseignant %}
                            {{matiere.enseignant}}
                        {% else %}
                            pas de prof
                        {% endif %}    
                    </td>                  
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main/templates/matieres/liste_matieres.html
{% extends '../index.html' %}

{% load static %}

{% block content %}
      <div class="content">
                    <!-- lal -->
                    <div class="block block-rounded mt-4">
                        <div class="block-header">
                          <h3 class="block-title">Affectation Matières : Page de confirmation</h3>
                          <a href="/main/affecter_matieres_prof" class="btn btn-sm btn-primary ml-3">AFFECTER DES MATIERES A UN PROFESSEUR</a>
  
                        </div>
                        <div class="block-content">
                            <table class="table table-borderless table-vcenter">
                              <thead>
                                <tr>
                                  <th class="text-center" style="width: 50px;">#</th>
                                  <th>Matière</th>
                                  <th class="d-none d-sm-table-cell" style="width: 15%;">Pondération</th>
                                  <th class="text-center" style="width: 100px;">Professeur</th>
                                  <th class="text-center" style="width: 100px;">Action</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for matiere in matieres %}
                                <tr>
                                  <th class="text-center" scope="row">{{ loop.index }}</th>
                                  <td class="font-w600 font-size-sm">{{ matiere.libelle }}</td>
                                  <td class="d-none d-sm-table-cell text-right">{{ matiere.ponderation }}</td>
                                  {% if matiere.enseignant %}
                                    <td class="text-center">{{ matiere.enseignant.nom }}  {{ matiere.enseignant.prenom }}</td>
                                    {% else %}
                                        <td class="text-center">Pas de professeur</td>
                                    {% endif %}
                                    <td class="text-center">
                                    <div class="btn-group">
                                      <button type="button" class="btn btn-alt-danger">Action</button>
                                      <button type="button" class="btn btn-alt-danger dropdown-toggle dropdown-toggle-split" id="dropdown-split-alt-danger" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                      </button>
                                      <div class="dropdown-menu font-size-sm" aria-labelledby="dropdown-split-alt-danger">
                                        <a class="dropdown-item" href="/main/retirer_professeur/{{matiere.id }}">Retirer le professeur</a>
                                            <a class="dropdown-item" href="#" data-toggle="modal" data-matiere-id="{{ matiere.id }}" data-target="#modal-block-slideright">Modifier la pondération</a>
                                      </div>
                                    </div>
                                  </td>
                                </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                          </div>
                          
                          <div class="modal fade" id="modal-block-slideright" tabindex="-1" role="dialog" aria-labelledby="modal-block-slideright" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-slide-right" role="document">
                              <div class="modal-content">
                                <div class="block block-themed block-transparent mb-0">
                                  <div class="block-header bg-primary-dark">
                                    <h3 class="block-title">Nouvelle Ponderation</h3>
                                    <div class="block-options">
                                      <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                                        <i class="fa fa-fw fa-times"></i>
                                      </button>
                                    </div>
                                  </div>
                                  <div class="block-content">
                                    <p class="font-size-sm text-muted">
                                      Choisissez votre nouvelle ponderation
                                    </p>
                                    <input type="hidden" name="matiere_id" id="matiere_id" value="">

                                    <div class="dropdown dropright push">
                                      <button type="button" class="btn btn-alt-primary dropdown-toggle" id="dropdown-dropright-alt-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Nouvelle Ponderation
                                      </button>
                                      <div class="dropdown-menu font-size-sm" aria-labelledby="dropdown-dropright-alt-primary">
                                        <a class="dropdown-item" href="/main/modifier_ponderation/{{dd}}/1">1</a>
                                        <a class="dropdown-item" href="/main/modifier_ponderation/{{dd}}/2">2</a>
                                        <a class="dropdown-item" href="/main/modifier_ponderation/{{dd}}/3">3</a>

                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                                                   
         </div>

          <script>
            $('.matiere').change(function() {
                var matiere = $(this).attr('id');
                var ponderation = $('#' + matiere + '-ponderation');
                if ($(this).is(':checked')) {
                    ponderation.removeClass('d-none');
                } else {
                    ponderation.addClass('d-none');
                }
            });
            $('#modal-block-slideright').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var matiere_id = button.data('matiere-id');
                var modal = $(this);
                modal.find('#matiere_id').val(matiere_id);
            });
            var modalTrigger = document.querySelector('[data-target="#modal-block-slideright"]');
            modalTrigger.addEventListener('click', function() {
            var matiereId = this.getAttribute('data-matiere-id');
            var links = document.querySelectorAll('#modal-block-slideright .dropdown-menu a');
            for (var i = 0; i < links.length; i++) {
                var href = links[i].getAttribute('href');
                href = href.replace('{{dd}}', matiereId);
                links[i].setAttribute('href', href);
            }
            var matiereIdField = document.querySelector('#matiere_id');
            matiereIdField.value = matiereId;
});
</script>

{% endblock %}
                      

main/templates/matieres/matiere_par_semestre.html
{% extends '../index.html' %}

{% block content %}
<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Liste des matières</h3>
        <a href="{% url 'main:create_matiere' %}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i> Ajout Matière
        </a>
    </div>
    <div class="block-content block-content-full">
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full-pagination">
            <thead>
                <tr>
                    <th class="text-center" style="width: 14%;">Code matière</th>
                    <th class="text-center" style="width: 20%;">Libéllé</th>
                    <th class="text-center" style="width: 40px;">Coefficient</th>
                    <th class="text-center" style="width: 50px;">Valeur minimale</th>
                    <th class="text-center" style="width: 20%;">Enseignant</th>
                    <th scope="col" class="bg-warning" style="width: 15%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for matiere in matieres_semestre %}
                <tr>
                    <td class="text-center font-size-sm">{{matiere.codematiere}}</td>
                    <td class="text-center font-size-sm">{{matiere.libelle}}</td>                  
                    <td class="text-center font-size-sm">{{matiere.coefficient}}</td>                  
                    <td class="text-center font-size-sm">{{matiere.minValue}}</td>                  
                    <td class="text-center font-size-sm">
                        {% if matiere.enseignant %}
                            {{matiere.enseignant}}
                        {% else %}
                            pas de prof
                        {% endif %} 
                    <td style="text-align: center;">                                       
                        <button type="button" class="bs-modal read-book btn btn-sm btn-primary">
                            <a style="color: blanchedalmond;" href="{% url 'main:detail_matiere' matiere.id %}">
                                <span class="fa fa-eye"></span>                
                            </a>
                        </button>
               
                        <button type="button" class="update-book btn btn-sm btn-warning">
                            <a style="color: blanchedalmond;" href="{% url 'main:update_matiere' matiere.id %}">
                                <span><i class="far fa-edit fa-lg"></i></span>
                        </button>                                     
                    </td> 
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main/templates/matieres/matieres.html
{% extends '../index.html' %}

{% block content %}

<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Liste des matières</h3>
        <a href="{% url 'main:create_matiere' %}" class="btn btn-outline-primary">
            <i class="fas fa-plus"></i> Ajout Matière
        </a>
    </div>
    <div class="block-content block-content-full">
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full-pagination">
            <thead>
                <tr>
                    <th class="text-center" style="width: 14%;">Code matière</th>
                    <th class="text-center" style="width: 20%;">Libéllé</th>
                    <th class="text-center" style="width: 40px;">Coefficient</th>
                    <th class="text-center" style="width: 50px;">Valeur minimale</th>
                    <th class="text-center" style="width: 20%;">Enseignant</th>
                    <th scope="col" class="bg-warning" style="width: 15%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for matiere in matieres %}
                <tr>
                    <td class="text-center font-size-sm">{{matiere.codematiere}}</td>
                    <td class="text-center font-size-sm">
                        <a href="{% url 'main:evaluations' matiere.id %}">{{matiere.libelle}}</a>
                    </td>                  
                    <td class="text-center font-size-sm">{{matiere.coefficient}}</td>                  
                    <td class="text-center font-size-sm">{{matiere.minValue}}</td>                  
                    <td class="text-center font-size-sm">
                        {% if matiere.enseignant %}
                            {{matiere.enseignant}}
                        {% else %}
                            pas de prof
                        {% endif %}                            
                        </td> 
                    <td style="text-align: center;">                                       
                        <button type="button" class="bs-modal read-book btn btn-sm btn-primary">
                            <a style="color: blanchedalmond;" href="{% url 'main:detail_matiere' matiere.id %}">
                                <span class="fa fa-eye"></span>                
                            </a>
                        </button>
               
                        <button type="button" class="update-book btn btn-sm btn-warning">
                            <a style="color: blanchedalmond;" href="{% url 'main:update_matiere' matiere.id %}">
                                <span><i class="far fa-edit fa-lg"></i></span>
                        </button>                                     
                    </td> 
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}