main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    
    
    
    path('dashboard', views.dashboard, name='dashboard'),
    path('affecter_matieres_prof', views.affectation_matieres_professeur, name='affectation_matieres_professeur'),
    path('liste_matieres_professeur',views.liste_matieres_professeur,name='liste_matieres_professeur'),
    path('retirer_professeur/<int:id>', views.retirer_professeur, name='retirer_professeur'),
    path('modifier_ponderation/<int:matiere_id>/<int:nouvelle_ponderation>/', views.modifier_ponderation, name='modifier_ponderation'),
    path('cahier_de_text/', views.cahier_de_text, name='cahier_de_text'),
    path('enregistrer_seance/', views.enregistrer_seance, name='enregistrer_seance'),
    path('modifier_seance/<int:seance_id>/', views.modifier_seance, name='modifier_seance'),
    path('liste_seance/', views.liste_seance, name='liste_seance'),
    path('liste_seance_etudiant/', views.liste_seance_etudiant, name='liste_seance_etudiant'),
    path('info_seance/<int:seance_id>/', views.info_seance, name='info_seance'),
    path('valider_seance/<int:seance_id>/', views.valider_seance, name='valider_seance'),
    path('connexion',views.login_view,name='connexion'),
    path('reminder',views.recuperation_mdp,name='reminder'),
    path('deconnexion',views.logout_view,name='deconnexion'),
    path('changer_secretaire',views.changer_secretaire,name='changer_secretaire'),
    path('gestion_classe',views.gestion_classe,name='gestion_classe'),



    # touré-ydaou urls templates latex 30-04-2023

    path('etudiants-l1', views.etudiants_l1, name='etudiants_l1'),
    path('etudiants-l2', views.etudiants_l2, name='etudiants_l2'),
    path('etudiants-l3', views.etudiants_l3, name='etudiants_l3'),


    path('carte-etudiant/<str:id>/<str:niveau>', views.carte_etudiant, name='carte_etudiant'),
    path('diplome/<str:id>', views.diplome_etudiant, name='diplome_etudiant'),
    path('certificat_scolaire/<str:id>/<str:niveau>', views.certificat_scolaire, name='certificat_scolaire'),
    path('releve_notes/<str:id>/<str:id_semestre>', views.releve_notes, name='releve_notes'),
    path('releve_note_detail/<str:id>/<str:id_semestre>', views.releve_notes_detail, name="releve_notes_detail"),

    # urls permettant de générer les documents de manière groupée (pour un ensemble d'étudiants)
    path('releve_notes/<str:id_semestre>', views.releve_notes_semestre, name='releve_notes'),
    path('carte-etudiant/<str:niveau>', views.carte_etudiant_all, name='carte_etudiant'),
    path('diplomes', views.diplome_etudiant_all, name='diplome_etudiant'),



    # Abdoul-Malik urls notes
    path('evaluations/<int:id_matiere>', views.evaluations, name='evaluations'),
    path('add_evaluation/<int:id_matiere>', views.createNotesByEvaluation, name='add_evaluation'),
    path('edit_evaluation/<int:id>', views.editeNoteByEvaluation, name='edit_evaluation'),
    path('delete_evaluation/<int:id>', views.deleteEvaluation, name='delete_evaluation'),


                               #### Étudiants ####
    path('liste_des_etudiants/', views.etudiants, name='liste_des_etudiants'),
    path('liste_des_etudiants_suspendu/', views.etudiants_suspendu, name='liste_des_etudiants_suspendu'),
    path('detail_etudiant/<str:id>/', views.detailEtudiant, name='detail_etudiant'),    
    path('create_etudiant/', views.create_etudiant, name='create_etudiant'),
    path('update_etudiant/<str:id>/', views.create_etudiant, name='update_etudiant'),   
   
   
                            #### Tuteurs ####
    path('liste_des_tuteurs/', views.tuteurs, name='liste_des_tuteurs'),
    path('detail_tuteur/<int:id>/', views.detailTuteur, name='detail_tuteur'),
    path('create_tuteur/', views.create_tuteur, name='create_tuteur'),
    path('update_tuteur/<int:id>/', views.create_tuteur, name='update_tuteur'),



                            #### Matières ####
    path('liste_des_matieres/', views.matieres, name='liste_des_matieres'),
    path('detail_matiere/<int:id>/', views.detailMatiere, name='detail_matiere'),
    path('create_matiere/', views.create_matiere, name='create_matiere'),
    path('update_matiere/<int:id>/', views.create_matiere, name='update_matiere'),

   

    path('matieres/semestre/1/', views.matiere_semestre, {'semestre': 1}, name='matiere_semestre1'),
    path('matieres/semestre/2/', views.matiere_semestre, {'semestre': 2}, name='matiere_semestre2'),
    path('matieres/semestre/3/', views.matiere_semestre, {'semestre': 3}, name='matiere_semestre3'),
    path('matieres/semestre/4/', views.matiere_semestre, {'semestre': 4}, name='matiere_semestre4'),
    path('matieres/semestre/5/', views.matiere_semestre, {'semestre': 5}, name='matiere_semestre5'),
    path('matieres/semestre/6/', views.matiere_semestre, {'semestre': 6}, name='matiere_semestre6'),




                            #### UEs ####
    path('liste_des_ues/', views.ues, name='liste_des_ues'),
    path('detail_ue/<int:id>/', views.detailUe, name='detail_ue'),
    path('create_ue/', views.create_ue, name='create_ue'),
    path('update_ue/<int:id>/', views.create_ue, name='update_ue'),

                        
                            ### UE par semestre
    path('ues_semestre/semestre1/', views.ues_semestre, {'semestre': 'S1'}, name='ues_semestre1'),
    path('ues_semestre/semestre2/', views.ues_semestre, {'semestre': 'S2'}, name='ues_semestre2'),
    path('ues_semestre/semestre3/', views.ues_semestre, {'semestre': 'S3'}, name='ues_semestre3'),
    path('ues_semestre/semestre4/', views.ues_semestre, {'semestre': 'S4'}, name='ues_semestre4'),
    path('ues_semestre/semestre5/', views.ues_semestre, {'semestre': 'S5'}, name='ues_semestre5'),
    path('ues_semestre/semestre6/', views.ues_semestre, {'semestre': 'S6'}, name='ues_semestre6'),



                            #### Enseignant ####
    path('create_enseignant/', views.create_enseignant, name='create_enseignant'),
    path('enseignant_list/', views.enseignant_actif, name='enseignant_list'),
    path('enseignant_suspendu/', views.enseignant_inactif, name='enseignant_suspendu'),
    path('enseignant_detail/(?P<id>[0-9]+)\\Z/', views.enseignant_detail, name='enseignant_detail'),
    path('edit_enseignant/(?P<id>[0-9]+)\\Z/', views.edit_enseignant, name='edit_enseignant'),
    path('certificat_travail/(?P<id>[0-9]+)\\Z/', views.certificat_travail, name='certificat_travail'),

                        ### Information ###
    path('information_list/', views.information_list, name='information_list'),
    path('information_detail/(?P<id>[0-9]+)\\Z/', views.information_detail, name='information_detail'),
    path('create_information/', views.create_information, name='create_information'),
    path('edit_information/(?P<id>[0-9]+)\\Z/', views.edit_information, name='edit_information'),




## Malia clôture des semestres
    path('semestres/', views.semestres_courants, name='semestres'),
    path('semestres_clotures/', views.semestres_clotures, name='semestres_clotures'),
    path('cloturer_semestre/<str:semestre_id>/', views.cloturer_semestre, name='cloturer_semestre'),
    path('reactiver_semestre/<str:semestre_id>/', views.reactiver_semestre, name='reactiver_semestre'),


## Historique des semestres :
    path('semestre/<str:semestre_id>/historique/', views.historique_semestre, name='historique_semestre'),



### Liste des étudiants par semestres 
    path('liste-etudiants/semestre1/', views.liste_etudiants_par_semestre, {'semestre': 'S1'}, name='liste_etudiants_semestre1'),
    path('liste-etudiants/semestre2/', views.liste_etudiants_par_semestre, {'semestre': 'S2'}, name='liste_etudiants_semestre2'),
    path('liste-etudiants/semestre3/', views.liste_etudiants_par_semestre, {'semestre': 'S3'}, name='liste_etudiants_semestre3'),
    path('liste-etudiants/semestre4/', views.liste_etudiants_par_semestre, {'semestre': 'S4'}, name='liste_etudiants_semestre4'),
    path('liste-etudiants/semestre5/', views.liste_etudiants_par_semestre, {'semestre': 'S5'}, name='liste_etudiants_semestre5'),
    path('liste-etudiants/semestre6/', views.liste_etudiants_par_semestre, {'semestre': 'S6'}, name='liste_etudiants_semestre6'),

    path('passage_etudiants/', views.passage_etudiants, name='passage_etudiants'),












]

paiement/urls.py
from django.urls import path
from . import views

app_name = 'paiement'

urlpatterns = [

                            #### Comptable ####
    path('create_comptable/', views.create_comptable, name='create_comptable'),
    path('comptable_detail/(?P<id>[0-9]+)\\Z/', views.comptable_detail, name='comptable_detail'),
    path('edit_comptable/(?P<id>[0-9]+)\\Z/', views.edit_comptable, name='edit_comptable'),
    path('comptable_list/', views.comptable_list, name='comptable_list'),


                            #### Paiement ####
    path('paiement_list/', views.paiement_list, name='paiement_list'),
    path('paiement_detail/(?P<id>[0-9]+)\\Z/', views.paiement_detail, name='paiement_detail'),
    path('create_paiement/', views.create_paiement, name='create_paiement'),
    path('edit_paiement/(?P<id>[0-9]+)\\Z/', views.edit_paiement, name='edit_paiement'),
    
                            #### Fiche de Paie ####
                            
    # URL pour lister toutes les fiches de paie
    path('fiche_de_paie_list/', views.fiche_de_paie_list, name='fiche_de_paie_list'),

    # URL pour afficher les détails d'une fiche de paie
    path('fiche_de_paie_detail/<int:id>/', views.fiche_de_paie_detail, name='fiche_de_paie_detail'),

    # URL pour créer une nouvelle fiche de paie
    path('create_fiche_de_paie/', views.create_fiche_de_paie, name='create_fiche_de_paie'),

    # URL pour mettre à jour une fiche de paie existante
    path('update_fiche_de_paie/<int:id>/', views.update_fiche_de_paie, name='update_fiche_de_paie'),
    
     # URL pour générer le fichier PDF de la fiche de paie
    path('fiche_paie/<int:id>/', views.fiche_paie, name='fiche_paie'),
    
    

]

projet_ifnti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('maquette/', include('maquette.urls')),
    path('historique/', include('historiques.urls')),
    path('paiement/', include('paiement.urls')),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paiement/models.py
from django.db import models
from main.models import *
# Create your models here.

paiement/views.py
from django.shortcuts import render
from main.models import *
from django.http import HttpResponse
import os
from django import forms
from django.http import FileResponse, HttpResponse
from django.shortcuts import render

from django import forms
from paiement.forms import ComptableForm, FicheDePaieForm, PaiementForm

import datetime
from main.pdfMaker import generate_pdf
from django.shortcuts import get_object_or_404, redirect, render




def create_comptable(request, id=0):
    if request.method == 'GET':
        if id == 0:
            form = ComptableForm()
        else:
            comptable = Comptable.objects.get(pk=id)
            form = ComptableForm(instance=comptable)
        return render(request, 'comptables/create_comptable.html', {'form': form})
    else:
        if id == 0:
            form = ComptableForm(request.POST)
        else:
            comptable = Comptable.objects.get(pk=id)
            form = ComptableForm(request.POST, instance=comptable)
        if form.is_valid():
            exit
            form.save()
            return redirect('/paiement/comptable_list')
        else:
            return render(request, 'comptables/create_comptable.html', {'form': form})
    


def comptable_detail(request, id):
    comptable = get_object_or_404(Comptable, id=id)
    return render(request, 'comptables/comptable_detail.html', {'comptable': comptable})


def edit_comptable(request, id):
    comptable = Comptable.objects.get(id=id)
    
    if request.method == 'POST':
        form = ComptableForm(request.POST, request.FILES, instance=comptable)
        if form.is_valid():
            comptable = form.save(commit=False)
            comptable.save()
            return redirect('/paiement/comptable_list')
    else:
        form = ComptableForm(instance=comptable)
    
    return render(request, 'comptables/edit_comptable.html', {'form': form})


def comptable_list(request):
    comptables = Comptable.objects.all()
    return render(request, 'comptables/comptable_list.html', {'comptables': comptables})


def paiement_list(request):
    paiements = Paiement.objects.all()
    return render(request, 'paiements/paiement_list.html', {'paiements': paiements})

def paiement_detail(request, id):
    paiement = Paiement.objects.get(id=id)
    return render(request, 'paiements/paiement_detail.html', {'paiement': paiement})

def create_paiement(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = PaiementForm()
        else:
            paiement = Paiement.objects.get(pk=id)
            form = PaiementForm(instance=paiement)
        return render(request, "paiements/create_paiement.html", {'form': form})
    else:
        if id == 0:
            form = PaiementForm(request.POST)
        else:
            paiement = Paiement.objects.get(pk=id)
            form = PaiementForm(request.POST, instance=paiement)
        if form.is_valid():
            form.save()
            return redirect('/paiement/paiement_list')
        else:
            print(form.errors)
            return render(request, "paiements/create_paiement.html", {'form': form})

def edit_paiement(request, id):
    paiement = Paiement.objects.get(id=id)
    if request.method == 'POST':
        form = PaiementForm(request.POST, instance=paiement)
        if form.is_valid():
            form.save()
            return redirect('/paiement/paiement_list')
    else:
        form = PaiementForm(instance=paiement)
        form.fields['montant'].initial = 0  # Définir la valeur par défaut à zéro
    return render(request, 'paiements/edit_paiement.html', {'form': form})


def fiche_de_paie_list(request):
    fiches = FicheDePaie.objects.all()
    return render(request, 'fichePaies/fiche_de_paie_list.html', {'fiches': fiches})

def fiche_de_paie_detail(request, id):
    fiche_de_paie = get_object_or_404(FicheDePaie, id=id)
    return render(request, 'fichePaies/fiche_de_paie_detail.html', {'fiche_de_paie': fiche_de_paie})

def create_fiche_de_paie(request):
    if request.method == "POST":
        form = FicheDePaieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/paiement/fiche_de_paie_list')
    else:
        form = FicheDePaieForm()

    return render(request, 'fichePaies/create_fiche_de_paie.html', {'form': form})

def update_fiche_de_paie(request, id):
    fiche_de_paie = get_object_or_404(FicheDePaie, id=id)

    if request.method == "POST":
        form = FicheDePaieForm(request.POST, instance=fiche_de_paie)
        if form.is_valid():
            form.save()
            return redirect('/paiement/fiche_de_paie_list')
    else:
        form = FicheDePaieForm(instance=fiche_de_paie)

    return render(request, 'fichePaies/update_fiche_de_paie.html', {'form': form})



def fiche_paie(request, id):
    fiche_paie = get_object_or_404(FicheDePaie, id=id)
    context = {'fiche_paie': fiche_paie}

    # nom des fichiers d'entrée et de sortie
    latex_input = 'fiche_paie'
    latex_ouput = 'generated_fiche_paie'
    pdf_file = 'pdf_fiche_paie'

    # génération du pdf
    generate_pdf(context, latex_input, latex_ouput, pdf_file)

    #visualisation du pdf dans le navigateur
    with open('media/pdf/' + str(pdf_file) + '.pdf', 'rb') as f:
        pdf_preview = f.read()
        response = HttpResponse(pdf_preview, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=pdf_file.pdf'
        return response

paiement/templates/fichePaies/fiche_de_paie_detail.html
{% extends '../index.html' %}

{% block content %}

<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Détails de la Fiche de Paie</h3>
    </div>

    <div class="block-content block-content-full">
        <table class="table table-bordered table-striped">
            <tr>
                <th>ID</th>
                <td>{{ fiche_de_paie.id }}</td>
            </tr>
            <tr>
                <th>B.P</th>
                <td>{{ fiche_de_paie.bp }}</td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ fiche_de_paie.telephone }}</td>
            </tr>
            <tr>
                <th>Date de début</th>
                <td>{{ fiche_de_paie.dateDebut }}</td>
            </tr>
            <tr>
                <th>Date de fin</th>
                <td>{{ fiche_de_paie.dateFin }}</td>
            </tr>
            <tr>
                <th>Niveau 1</th>
                <td>{{ fiche_de_paie.niveau1 }}</td>
            </tr>
            <tr>
                <th>Niveau 2</th>
                <td>{{ fiche_de_paie.niveau2 }}</td>
            </tr>
            <tr>
                <th>Niveau 3</th>
                <td>{{ fiche_de_paie.niveau3 }}</td>
            </tr>
            <tr>
                <th>Matière</th>
                <td>{{ fiche_de_paie.matiere }}</td>
            </tr>
            <tr>
                <th>Enseignant</th>
                <td>{{ fiche_de_paie.enseignant }}</td>
            </tr>
            <tr>
                <th>Heure en L1</th>
                <td>{{ fiche_de_paie.heureL1 }}</td>
            </tr>
            <tr>
                <th>Heure en L2</th>
                <td>{{ fiche_de_paie.heureL2 }}</td>
            </tr>
            <tr>
                <th>Heure en L3</th>
                <td>{{ fiche_de_paie.heureL3 }}</td>
            </tr>
            <tr>
                <th>Montant en L1</th>
                <td>{{ fiche_de_paie.montantL1 }}</td>
            </tr>
            <tr>
                <th>Montant en L2</th>
                <td>{{ fiche_de_paie.montantL2 }}</td>
            </tr>
            <tr>
                <th>Montant en L3</th>
                <td>{{ fiche_de_paie.montantL3 }}</td>
            </tr>
            <tr>
                <th>Nombre d'heure Total</th>
                <td>{{ fiche_de_paie.nombreHeure }}</td>
            </tr>
            <tr>
                <th>Prix unitaire</th>
                <td>{{ fiche_de_paie.prixUnitaire }}</td>
            </tr>
            <tr>
                <th>Montant Total</th>
                <td>{{ fiche_de_paie.montantTotal }}</td>
            </tr>
            <tr>
                <th>Montant Avance</th>
                <td>{{ fiche_de_paie.montantAvance }}</td>
            </tr>
            <tr>
                <th>Montant à payer</th>
                <td>{{ fiche_de_paie.montantAPayer }}</td>
            </tr>
            <tr>
                <th>Montan en lettre</th>
                <td>{{ fiche_de_paie.montantEnLettre }}</td>
            </tr>
            <tr>
                <th>Numero</th>
                <td>{{ fiche_de_paie.numero }}</td>
            </tr>
            
        </table>
        <div class="form-group">
            <a href="{% url 'paiement:fiche_de_paie_list' %}" class="btn btn-secondary">Retour à la liste</a>
        </div>
    </div>
</div>

{% endblock %}

paiement/templates/fichePaies/fiche_de_paie_list.html
{% extends '../index.html' %}

{% block content %}

<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Liste des Fiches de Paie</h3>
        <a href="{% url 'paiement:create_fiche_de_paie' %}">
            <button type="button" class="btn btn-secondary float-right" id="dropdown-default-secondary" aria-haspopup="true" aria-expanded="false">
                Ajouter
            </button>
        </a>
    </div>

    <div class="block-content block-content-full">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full-pagination">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 80px;">ID</th>
                        <th class="text-center" style="width: 30%;">Date debut</th>
                        <th class="text-center" style="width: 30%;">Date Fin</th>
                        <th class="text-center" style="width: 80px;">Niveau1</th>
                        <th class="text-center" style="width: 80px;">Niveau2</th>
                        <th class="text-center" style="width: 80px;">Niveau3</th>
                        <th class="text-center" style="width: 30%;">Matière</th>
                        <th class="text-center" style="width: 30%;">Enseignant</th>
                        <th class="text-center" style="width: 15%;">Nombre d'heure</th>
                        <th class="text-center" style="width: 15%;">Prix unitaire</th>
                        <th class="text-center" style="width: 15%;">Montant Total</th>
                        <th class="text-center" style="width: 15%;">Montant avance</th>
                        <th class="text-center" style="width: 15%;">Montant à payer</th>
                        <th class="text-center" style="width: 15%;">Montant En lettre</th>
                        <th class="text-center" style="width: 15%;">Heure en L1</th>
                        <th class="text-center" style="width: 15%;">Heure en L2</th>
                        <th class="text-center" style="width: 15%;">Heure en L3</th>

                        <th class="text-center" style="width: 55%;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fiche in fiches %}
                    <tr>
                        <td class="text-center font-size-sm">{{ fiche.id }}</td>
                        <td class="text-center font-size-sm">{{ fiche.dateDebut }}</td>
                        <td class="text-center font-size-sm">{{ fiche.dateFin }}</td>
                        <td class="text-center font-size-sm">{{ fiche.niveau1 }}</td>
                        <td class="text-center font-size-sm">{{ fiche.niveau2 }}</td>
                        <td class="text-center font-size-sm">{{ fiche.niveau3 }}</td>
                        <td class="text-center font-size-sm">{{ fiche.matiere }}</td>
                        <td class="text-center font-size-sm">{{ fiche.enseignant }}</td>
                        <td class="text-center font-size-sm">{{ fiche.nombreHeure }}</td>
                        <td class="text-center font-size-sm">{{ fiche.prixUnitaire }}</td>
                        <td class="text-center font-size-sm">{{ fiche.montantTotal }}</td>
                        <td class="text-center font-size-sm">{{ fiche.montantAvance }}</td>
                        <td class="text-center font-size-sm">{{ fiche.montantAPayer }}</td>
                        <td class="text-center font-size-sm">{{ fiche.montantEnLettre }}</td>
                        <td class="text-center font-size-sm">{{ fiche.heureL1 }}</td>
                        <td class="text-center font-size-sm">{{ fiche.heureL2 }}</td>
                        <td class="text-center font-size-sm">{{ fiche.heureL3 }}</td>
                        <td style="text-align: center;">
                            <button type="button" class="bs-modal read-book btn btn-sm btn-primary">
                                <a style="color: blanchedalmond;" href="{% url 'paiement:fiche_de_paie_detail' fiche.id %}">
                                    <span class="fa fa-eye"></span>
                                </a>
                            </button>

                            <button type="button" class="update-book btn btn-sm btn-warning">
                                <a style="color: blanchedalmond;" href="{% url 'paiement:update_fiche_de_paie' fiche.id %}">
                                    <span><i class="far fa-edit"></i></span>
                                </a>
                            </button>

                            <button type="button" class="update-book btn btn-sm btn-success">
                                <a  style="color: blanchedalmond;" href="{% url 'paiement:fiche_paie' fiche.id %}">
                                    <span><i class="fas fa-file-pdf"></i></span>
                                </a>
                            </button>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

paiement/templates/fichePaies/update_fiche_de_paie.html
{% extends '../index.html' %}

{% block content %}

<div class="block block-rounded m-5">
    <div class="block-header p-4">
        <h3 class="block-title">Modifier la Fiche de Paie</h3>
    </div>

    <div class="block-content block-content-full">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="form-group">
                <button type="submit" class="btn btn-warning">Modifier</button>
                <a href="{% url 'paiement:fiche_de_paie_list' %}" class="btn btn-secondary">Annuler</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}